language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r .travis/requirements.txt
  - nvm install v12.16.1
  - npm install
  - npm i -g purgecss
  - npm i -g postcss postcss-cli
  - npm i cssnano
# command to run tests
script: python .travis/build.py
before_deploy: 
  - purgecss -c ./purgecss.config.js --output assets/css/
  - cat ./assets/css/*.css | postcss --no-map > ./assets/css/bundle.min.css
cache:
  directories:
    - node_modules
deploy:
  provider: netlify
  site: $NETLIFY_SITE
  auth: $NETLIFY_AUTH
  dir: .
  prod: true
  edge: true # opt in to dpl v2
 
