---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: document
  path: data/press.json
  label: Press
- type: document
  path: data/foss-contributions.json
  label: FOSS Contributions
- type: document
  path: data/timeline.json
  label: Timeline
- type: document
  path: data/backpack.json
  label: Backpack
- type: document
  path: data/projects.json
  label: Projects
- type: document
  path: data/settings.json
  label: Site Settings
upload_dir: assets
public_path: "/assets"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
